resources:
  - name: bvt_keys
    type: integration
    integration: bvt_keys

  - name: bvt_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/bvt
      branch: master

jobs:
  - name: bvt
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: bvt_repo
        switch: off
      - IN: bvt_keys
        switch: off
      - IN: rc_deploy
        switch: off
      - TASK:
          name: execute_bvt
          runtime:
            options:
              env:
                - TEST_MANUAL: true
          script:
            - pushd $(shipctl get_resource_state "bvt_repo")
            - shipctl copy_file_from_prev_state conf.json .
            - if [[ -s conf.json ]]; then echo "{}" > conf.json; fi
            - ./test.sh
            - popd
    on_failure:
      - NOTIFY: rc_slack
    always:
      script:
        - pushd $(shipctl get_resource_state "bvt_repo")
        - shipctl copy_file_to_state conf.json
        - popd
